### ISSUE TITLE
people.opml.bak and reinitialization

### ISSUE THREAD

**Issue by 7tonin** [moonmoon/moonmoon#83] opened 2017-04-21 15:54 UTC
Hi,
after a while, my people.opml file is renamed people.opml.bak and a brand new one is created, with no people inside. As a result, the aggregation becomes empty (Good news !).
I wonder what's going on ?
I'm on a PHP 5.6.30 environment on linux, and I don't see any clue in tail -f /var/log/httpd/error_log
What can be done to debug this ?

**Comment by nashe** [comment] 2017-04-21 16:02
Aloha,

The function responsible of the `.bak` file creation is [`opml::backup`](https://github.com/mauricesvay/moonmoon/blob/23267b401439199a8bf3d5c9733f70d5d0e3d3d1/app/lib/lib.opml.php#L107) and is called [when a new feed is added](https://github.com/mauricesvay/moonmoon/blob/23267b401439199a8bf3d5c9733f70d5d0e3d3d1/admin/subscriptions.php#L60). Thus, I suppose that you added a new feed but that the creation of the new `people.opml` file failed. Is it the case? Can you share the URLs you tried to add?

**Comment by 7tonin** [comment] 2017-04-21 16:37
I don't remember precisely what preceded the bug. The .bak file did not contain my latest modifications ( which consisted in renaming some feed titles in admin panel). but these changes have been saved since a copy of the moonmoon html page proves it. So I'm thinking about a third part action replacing de people.opml file without backup.
Give me some time to make sure, that's 2nd time I see the aggregation feed empty with no apparent reason.

**Comment by nashe** [comment] 2017-04-21 16:44
The latests modifications are not supposed to be in the backup file since it's copied before the new content to be put into `people.opml`, so this part is OK :-)
It's also possible that in one way or another (eg. frontend issue), you are asking for deleting of all your feeds. I'll take a look at this as soon as possible and try to reproduce your issue.

**Comment by 7tonin** [comment] 2017-04-25 09:17
I do agree. But the new content was gone, while moonmoon home page had been saved with the new content. So there is something weird.
Yesterday evening, I loaded my moonmoon page. This morning I checked my directory : ls -al rss/custom/
```total 52
drwxrwxr-x 5 myself webgrp  4096 avril 21 18:09 ./
drwxrwxr-x 8 myself webgrp  4096 avril 21 18:39 ../
-rw-r--r-- 1 myself myself   238 avril 20 00:10 config.yml
-rw-r--r-- 1 myself webgrp 10244 janv. 24 20:48 .DS_Store
drwxr-xr-x 2 myself webgrp  4096 mai    5  2010 img/
-rw-r--r-- 1 apache apache   204 avril 20 00:24 people.0.opml
-rw-r--r-- 1 apache apache  3453 avril 24 22:11 people.opml
-rw-r--r-- 1 apache apache  3456 avril 21 19:24 people.opml.bak
-rw-r--r-- 1 myself myself  3568 avril 20 21:27 people.opml.my.bak
drwxr-xr-x 2 myself webgrp  4096 janv. 24 20:55 style/
drwxr-xr-x 4 myself webgrp  4096 janv. 24 20:55 views/
```
As you can see people.ompl has been modified `avril 24 22:11`
When I look for differences : diff people.opml people.opml.bak 
```4,6c4,6
< <title>égation syndications RSS contrainte climat-énergie</title>
< <dateCreated>2017-04-24T22:11:30+02:00</dateCreated>
< <dateModified>2017-04-24T22:11:30+02:00</dateModified>
---
> <title>Agrégation syndications RSS contrainte climat-énergie</title>
> <dateCreated>2017-04-21T19:23:30+02:00</dateCreated>
> <dateModified>2017-04-21T19:23:30+02:00</dateModified>
```
I have looked for relevant lines in my server logs for moonmoon call on moonmoon script (in rss/) : /var/log/httpd/ssl_request_log
```
[24/Apr/2017:22:11:22 +0200] "GET /myhome/rss/ HTTP/1.1" 34177
[24/Apr/2017:22:11:24 +0200] "GET /myhome/rss/custom/style/default.css HTTP/1.1" 2006
[24/Apr/2017:22:11:31 +0200] "GET /myhome/rss/custom/img/opml.png HTTP/1.1" 31542
```
and in /var/log/httpd/access_log, because there is a feed from the server itself made by a homemade php script
```
[24/Apr/2017:22:11:27 +0200] "GET /myhome/rsskeywords/rsskeywords.php HTTP/1.1" 200 18500 "-" "SimplePie/1.3.1 (Feed Parser; http://simplepie.org; Allow like Gecko) Build/20121030165404"
```
You may be right... can this feed script generate a feed that makes SimplePie fool ?
This script loads several feeds and filter against some key words.
https://cftw.hd.free.fr/yaya/arfreefr/climat-energie/rsskeywords/rsskeywords.php
this is a fork from this one https://openclassrooms.com/forum/sujet/trier-un-flux-rss-par-mots-cles-68258#message-6807734

**Comment by lodi-g** [comment] 2017-05-17 11:39
Sorry, did not see this issue.
I'm Using moonmoon 9.0.0, downloaded from GitHub with PHP 5.6.30 on Debian 8 (jessie).

My people.opml seems to have been renamed to people.opml.bak as well. If you need anything else, lmk.

**Comment by nashe** [comment] 2017-05-22 22:35
I'm not able to reproduce this behaviour on a fresh 9.0-rc instance. I added more than 40 feeds without any issue. Can you please apply the following patch on `app/lib/lib.opml.php` and tell me if this happens again? Thanks!

```diff
@@ -70,14 +70,15 @@

 class OpmlManager
 {
-    static function load($file) {
+    public function load($file) {
         if (@file_exists($file)) {
             $opml = new opml();

-            //Remove BOM if needed
-            $BOM = '/^/';
             $fileContent = file_get_contents($file);
-            $fileContent = preg_replace($BOM, '', $fileContent, 1);
+
+            if ($fileContent === false) {
+                die('Something went wrong!');
+            }

             //Parse
             $opml->parse($fileContent);
@@ -101,7 +102,7 @@
         $out.= '</body>'."\n";
         $out.= '</opml>';

-        file_put_contents($file, $out);
+        file_put_contents($file, $out,  LOCK_EX);
     }

     public function backup($file){
```

**Comment by lodi-g** [comment] 2017-05-25 21:34
It doesn't seem to happens again so far. Thank you.

**Comment by nashe** [comment] 2017-05-28 11:20
@7tonin: can you also try this patch and tell me if you encounter again this issue? Thanks!

**Comment by 7tonin** [comment] 2017-05-29 21:31
I'm buzy now... but I have modified class OpmlManager like suggested.
In the code my load function was already public, but other changes comply with your patch description.

Then I loaded https://cftw.hd.free.fr/yaya/arfreefr/climat-energie/rss/ (needed a few seconds). All feeds seem to be present.
And then https://cftw.hd.free.fr/yaya/arfreefr/climat-energie/rss/admin/ (quick load). Every feed is gone (but are still present in backup file, ouf !)
...
Until today, I didn't notice anymore reproduction of the bug. So I would think about a regression or a problem with the admin login page. Hope you have a better guess.

**Comment by 7tonin** [comment] 2017-05-29 21:50
After some checks, reverse backup from a miror. I checked the users rights 
ls -al rss/custom/people.*
```
-rw-r--r-- 1 apache  apache     204 avril 20 00:24 people.0.opml
-rw-rw-r-- 1 myself  webgrp    3755 mai   29 23:33 people.opml
-rw-r--r-- 1 apache  apache    3752 mai    5 18:57 people.opml.bak
-rw-r--r-- 1 myself  myself    3752 mai    5 18:57 people.opml.my2.bak
-rw-r--r-- 1 myself  myself    3568 avril 20 21:27 people.opml.my.bak

```
the previous is stable, and no people removal bug happens.
If I change the 
`-rw-rw-r-- 1 myself  webgrp    3755 mai   29 23:33 people.opml`
with 
`-rw-r--r-- 1 apache  apache      204 mai   29 23:41 people.opml`
then the bug happens again.

After the bug occurs, here are the new files/rights
```
-rw-r--r-- 1 apache  apache    204 mai   29 23:41 people.opml
-rw-r--r-- 1 apache  apache   3752 mai    5 18:57 people.opml.bak
```

NB : webgrp members are apache and myself

**Comment by nashe** [comment] 2017-05-29 22:01
OK thanks for you feedback, I'm digging into `cron.php`.

**Comment by Emmafrs** [comment] 2017-07-05 09:47
I had the same problem yesterday a few times (5 maybe) and i don't know how or why it happened. I test a lot the code, cause i change it (simple modifications), and sometimes, when i refreshed the pages (the index or the admin), there was no people anymore, and i had to transfer my saved file people.opml again. 
I can't give you more informations, i really don't understand all the things you're talking in this page. 
I just can say i empty the cache few times in admin, test the results in my index page (i changed some part of the code in the index.tpl.php, testing it with or without the sidebar, with just a part of the sidebar code...), and sometimes, but not always, the people.opml file was new and empty. 
I did not add another feed during all the tests. My people.opml file contains 31 feeds. It was saved on my computer, so i had just have to reload it.

**Comment by zeus86** [comment] 2017-11-19 14:21
i just applied the patch provided by  @nashe  on a fresh version of 9.0.0-rc , but the problem still persists, moreover it seems to happen even more often! performing an action which would the people.opml cause to change will likely result in an empty file. beside that, after some time the people.opml also sometimes cleares out itself. it is pretty annoying to always copy back the backup-file (glad this is created!).

some specs:
- Ubuntu 16.04 LTS, x86_64 on 4.4.0 generic kernel
- nginx/1.10.3 
- PHP 7.0.22-0ubuntu0.16.04.1 (fpm-fcgi)

**Comment by zeus86** [comment] 2017-11-19 14:30
by the way, in my case the nginx-site also as the php-fpm-instance are running under a dedicated user for that, and all files are belonging to that user, before and after an "incident".

**Comment by zeus86** [comment] 2017-11-19 16:46
my workaround by now is making the people.opml immuteable (chattr +i people.opml), this prevents the file from beeing modified. when i want to change it, i remove the i-flag (-i), edit the file via a text-editor, and set it to immutable again istead of using the admin panel.

nevertheless, this is ugly and not really usable for a long-term solution.

**Comment by nashe** [comment] 2017-11-19 16:51
(I did not take time to fix this _awful_ issue and completely forgot it, I'm adding it to next week's todolist… Thanks for your feedback on it!)

**Comment by zeus86** [comment] 2017-11-19 16:53
sure^^ will there be a new release also? because the code does not compile on my system (maybe the install-guide is somewhat too old?) and i had to use the stable-rc.

**Comment by nashe** [comment] 2017-11-19 22:42
I need to close this issue first this to tag a new _beta_ (I had to broke too much things that I should never have been calling this a RC). Don't hesitate to use the nightly version and / or open issue(s) if you have any problem.

**Comment by nashe** [comment] 2018-01-04 22:11
@zeus86, @7tonin, @lodi-g: I finally published a release which should fix this issue, [`9.0.0-rc.3`](https://github.com/moonmoon/moonmoon/releases/tag/9.0.0-rc.3). Can you please give it a try and tell me if it happens again? Thanks in advance 👍

**Comment by nashe** [comment] 2018-03-22 20:15
Closing this ticket since there is no answer—don't hesitate to open it again if this bug comes back.

**Closed by nashe** 2018-03-22 20:15 UTC
Labels: bug

**Comment by zeus86** [comment] 2018-03-23 20:45
Oh yeah, forgot to report this back. At least everything seems to work normally with 9.0.0-rc.3. i have not encountered issues with that so far. :+1:

**Comment by Emmafrs** [comment] 2019-08-17 15:57
It happends for me this week (august 2019) : 38 feeds, I wasn't do anything in the admin, I just see 2 days after that nothing appears on the index and when i take a look my peaople.opml file was empty.
